image:
  repository: selcpacr.azurecr.io/uservicepartyregistryproxy
  pullPolicy: Always # TODO change me in IfNotPresent when each build will have a different tag
  tag: 0.1.8

ingress:
  annotations:
    nginx.ingress.kubernetes.io/cors-allow-origin: "https://selfcare.pagopa.it"

replicaCount: 1

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

configEnvSpecific:
  JAVA_OPTS: "-javaagent:/applicationinsights-agent.jar"
  APPLICATIONINSIGHTS_INSTRUMENTATION_LOGGING_LEVEL: "OFF"
  REQUIRED_CONTACT_POINT_NR: "1"
