image:
  repository: selcdacr.azurecr.io/uservicepartyregistryproxy
  tag: 0.1.12

ingress:
  annotations:
    nginx.ingress.kubernetes.io/cors-allow-origin: "https://dev.selfcare.pagopa.it,http://localhost:3000"

replicaCount: 1

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

configEnvSpecific:
  JAVA_OPTS: "-javaagent:/applicationinsights-agent.jar"
  APPLICATIONINSIGHTS_INSTRUMENTATION_LOGGING_LEVEL: "OFF"
  REQUIRED_CONTACT_POINT_NR: "1"
  MOCK_ORIGIN: "static"
  PARTY_MOCK_REGISTRY_INSTITUTIONS_URL: "https://selcdcheckoutsa.z6.web.core.windows.net/resources/ORIGIN-mock.json"
