image:
  repository: selcpacr.azurecr.io/uservicepartyregistryproxy
  pullPolicy: Always # TODO change me in IfNotPresent when each build will have a different tag
  tag: 0.1.12

ingress:
  annotations:
    nginx.ingress.kubernetes.io/cors-allow-origin: "https://selfcare.pagopa.it"

replicaCount: 1

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

configEnvSpecific:
  JAVA_OPTS: "-javaagent:/applicationinsights-agent.jar"
  APPLICATIONINSIGHTS_INSTRUMENTATION_LOGGING_LEVEL: "OFF"
  REQUIRED_CONTACT_POINT_NR: "1"
  PARTY_REGISTRY_INSTITUTIONS_URL: "https://selcpcheckoutsa.z6.web.core.windows.net/resources/IPA-mock.json"
  MOCK_ORIGIN: "static"
  PARTY_MOCK_REGISTRY_INSTITUTIONS_URL: "https://selcpcheckoutsa.z6.web.core.windows.net/resources/ORIGIN-mock.json"
  PARTY_MOCK_REGISTRY_CATEGORIES_URL: "https://indicepa.gov.it/ipa-dati/datastore/dump/84ebb2e7-0e61-427b-a1dd-ab8bb2a84f07?format=json"
